/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.Statement;
import javax.swing.*;
import java.sql.*;

/**
 *
 * @author gagne
 */
class mymodel1 extends javax.swing.table.AbstractTableModel{
    ResultSet rs;
    ResultSetMetaData rsmd;
    mymodel1(ResultSet rs1)
    {
        try
        {
            rs=rs1;
            rsmd=rs.getMetaData();
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }
    @Override
    public int getRowCount()
    {
        try
        {
            rs.last();
            return (rs.getRow());
        }
        catch(Exception e)
        {
            System.out.print(e);
            return -1;
        }
    }
    @Override
    public int getColumnCount()
    {
        try
        {
            return (rsmd.getColumnCount());
        }
        catch(Exception e)
        {
            System.out.print(e);
            return -1;
        }
    }
    @Override
    public Object getValueAt(int rowIndex, int columnIndex)
    {
        try
        {
            rs.absolute(rowIndex+1);
            if(columnIndex == 0)
        {
            return rowIndex + 1;
        }
            return rs.getObject(columnIndex+1);
        }
        catch(Exception e)
        {
            System.out.print(e);
            return -1;
        }
    }
    @Override
    public  String getColumnName(int n)
    {
        try
        {
            return rsmd.getColumnName(n+1);
        }
        catch(Exception e)
        {
            System.out.print(e);
            return null;
        }
    }
    }
public class ADMIN extends javax.swing.JFrame {

    /**
     * Creates new form ADMIN
     */
    ResultSet rs;
    public ADMIN() {
        initComponents();
        setTitle("KBC GAME");
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection( "jdbc:mysql://localhost:3306/kbc_game","root","");
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs = st.executeQuery("SELECT DISTINCT Category FROM questions");
            c2.removeAllItems();
            while(rs.next())
            {
            c2.addItem(rs.getString("Category"));
            }
            }
    catch(Exception e)
    {
        System.out.println(e);
    }
        this.setBounds(1, 1, 1880, 870);
        t1.setEditable(false);
        t8.setVisible(false);
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection C1=DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
            Statement St = C1.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs=St.executeQuery("Select distinct Category from questions");
            while(rs.next())
            {
                C.add(rs.getString(1));
            }
            C.add("Add New");
        }
        catch(Exception aa)
        {
            System.out.print(aa);
        }
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c=DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game", "root", "");
            Statement st=c.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs=st.executeQuery("SELECT MAX(`S.No`) FROM questions");
            if(rs.next())
            {
                int id=rs.getInt(1);
                id=id+1;
                t1.setText(String.valueOf(id));
            }
        }
        catch(Exception a)
        {
            System.out.print(a);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        l2 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        C = new java.awt.Choice();
        l1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        l4 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        t5 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        t7 = new javax.swing.JTextField();
        b1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt2 = new javax.swing.JTable();
        c2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(null);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/admin2.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(740, 10, 500, 110);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/admin3.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(1610, -10, 260, 280);

        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/cq.png"))); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(1590, 740, 200, 50);

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 2, true));
        jPanel2.setLayout(null);

        l2.setFont(new java.awt.Font("Rockwell Condensed", 1, 40)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 215, 0));
        l2.setText("CATEGORY");
        jPanel2.add(l2);
        l2.setBounds(600, 20, 180, 60);

        t8.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jPanel2.add(t8);
        t8.setBounds(800, 80, 260, 35);

        C.setBackground(new java.awt.Color(255, 215, 0));
        C.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        C.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                CItemStateChanged(evt);
            }
        });
        jPanel2.add(C);
        C.setBounds(800, 40, 260, 30);

        l1.setFont(new java.awt.Font("Rockwell Condensed", 1, 40)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 215, 0));
        l1.setText("S.No");
        jPanel2.add(l1);
        l1.setBounds(30, 20, 80, 50);

        t1.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel2.add(t1);
        t1.setBounds(120, 20, 160, 50);

        l3.setFont(new java.awt.Font("Rockwell Condensed", 1, 40)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 215, 0));
        l3.setText("QUESTION");
        jPanel2.add(l3);
        l3.setBounds(20, 140, 180, 50);

        t2.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        jPanel2.add(t2);
        t2.setBounds(200, 140, 860, 50);

        l4.setFont(new java.awt.Font("Rockwell Condensed", 1, 40)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 215, 0));
        l4.setText("OPTION 1");
        jPanel2.add(l4);
        l4.setBounds(20, 210, 200, 60);

        l5.setFont(new java.awt.Font("Rockwell Condensed", 1, 40)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 215, 0));
        l5.setText("OPTION 2");
        jPanel2.add(l5);
        l5.setBounds(20, 290, 200, 50);

        l6.setFont(new java.awt.Font("Rockwell Condensed", 1, 40)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 215, 0));
        l6.setText("OPTION 3");
        jPanel2.add(l6);
        l6.setBounds(20, 360, 200, 50);

        l7.setFont(new java.awt.Font("Rockwell Condensed", 1, 40)); // NOI18N
        l7.setForeground(new java.awt.Color(255, 215, 0));
        l7.setText("OPTION 4");
        jPanel2.add(l7);
        l7.setBounds(20, 430, 200, 50);

        l8.setFont(new java.awt.Font("Rockwell Condensed", 1, 40)); // NOI18N
        l8.setForeground(new java.awt.Color(255, 215, 0));
        l8.setText("ANSWER");
        jPanel2.add(l8);
        l8.setBounds(20, 500, 200, 50);

        t3.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jPanel2.add(t3);
        t3.setBounds(200, 220, 550, 50);

        t4.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jPanel2.add(t4);
        t4.setBounds(200, 290, 550, 50);

        t5.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jPanel2.add(t5);
        t5.setBounds(200, 360, 550, 50);

        t6.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jPanel2.add(t6);
        t6.setBounds(200, 430, 550, 50);

        t7.setFont(new java.awt.Font("Palatino Linotype", 1, 24)); // NOI18N
        jPanel2.add(t7);
        t7.setBounds(200, 500, 550, 50);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(30, 120, 1070, 580);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/sq.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(310, 740, 360, 50);

        jPanel3.setBackground(new java.awt.Color(10, 25, 70));
        jPanel3.setLayout(null);

        jt2.setBackground(new java.awt.Color(10, 25, 70));
        jt2.setFont(new java.awt.Font("Bookman Old Style", 1, 16)); // NOI18N
        jt2.setForeground(new java.awt.Color(255, 255, 255));
        jt2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "S.No", "CATEGORY", "QUESTION"
            }
        ));
        jt2.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jt2.setColumnSelectionAllowed(true);
        jt2.setRowHeight(35);
        jt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt2);

        jPanel3.add(jScrollPane1);
        jScrollPane1.setBounds(10, 130, 670, 360);

        c2.setBackground(new java.awt.Color(255, 215, 0));
        c2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        c2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c2ActionPerformed(evt);
            }
        });
        jPanel3.add(c2);
        c2.setBounds(450, 80, 230, 40);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/question1.png"))); // NOI18N
        jPanel3.add(jLabel3);
        jLabel3.setBounds(30, 20, 410, 100);

        jPanel1.add(jPanel3);
        jPanel3.setBounds(1120, 190, 690, 510);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/delete1.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(740, 740, 350, 50);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/update1.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1160, 740, 350, 50);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/bgadmin.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1910, 820);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1870, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        dispose();
        LOGIN L1 = new LOGIN();
        L1.setSize(1880,870);
        L1.setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
            if(t2.getText().trim().length()==0)
            {
               JOptionPane.showMessageDialog(this,"Please enter the Question !"); 
            }
        else
                if(t3.getText().trim().length()==0 || t4.getText().trim().length()==0 || t5.getText().trim().length()==0 || t6.getText().trim().length()==0)
                {
                     JOptionPane.showMessageDialog(this,"All 4 Options Must Be Filled !");
                }
        else
               if( t7.getText().trim().length()==0)
    {
        JOptionPane.showMessageDialog(this,"Answer Field Cannot Be Empty !");
    }
               else
                   if(t8.isVisible() && t8.getText().trim().length()==0)
                   {
                        JOptionPane.showMessageDialog(this,"Please fill in the Category !");
                   }
    else
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection c1=DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
            Statement st=c1.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            String itemValue=C.getSelectedItem().toString();
            if(itemValue.equals("Add New"))
            {
                itemValue=t8.getText();
            }
            int i =st.executeUpdate("insert into questions values('"+t1.getText()+"','"+itemValue+"','"+t2.getText()+"','"+t3.getText()+"','"+t4.getText()+"','"+t5.getText()+"','"+t6.getText()+"','"+t7.getText()+"')");
            if(i==1)
            {
                t1.setText("");
                if (C.getItemCount() > 0) {
        C.select(0);
    }
                t2.setText("");
                t3.setText("");
                t4.setText("");
                t5.setText("");
                t6.setText("");
                t7.setText("");
                ResultSet rs=st.executeQuery("SELECT MAX(`S.No`) FROM questions");
            if(rs.next())
            {
                int id=rs.getInt(1);
                id=id+1;
                t1.setText(String.valueOf(id));
            }
           }
            JOptionPane.showMessageDialog(this, "Question Added Successfully !");
        }
        catch(Exception e1)
        {
             e1.printStackTrace();
    JOptionPane.showMessageDialog(this, e1.getMessage());
        }
    }
    }//GEN-LAST:event_b1ActionPerformed

    private void CItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_CItemStateChanged
        // TODO add your handling code here:
        String s1 = C.getSelectedItem();
        if(s1.equals("Add New"))
        {
            t8.setVisible(true);
        }
        else
        {
            t8.setVisible(false);
        }
    }//GEN-LAST:event_CItemStateChanged

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void c2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c2ActionPerformed
        // TODO add your handling code here:
         try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection( "jdbc:mysql://localhost:3306/kbc_game","root","");
            String selectedCategory = c2.getSelectedItem().toString();
             Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
              rs = st.executeQuery("SELECT `S.No`, Category, Question FROM questions "+ "WHERE Category='" + selectedCategory + "'");
              mymodel1 m1 = new mymodel1(rs);
              jt2.setModel(m1);
              jt2.getColumnModel().getColumn(0).setPreferredWidth(40);
              jt2.getColumnModel().getColumn(1).setPreferredWidth(180);
              jt2.getColumnModel().getColumn(2).setPreferredWidth(800);
        }
         catch(Exception e)
         {
             System.out.print(e);
         }
    }//GEN-LAST:event_c2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
         try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
                Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                String category = C.getSelectedItem();
                st.executeUpdate("UPDATE questions SET "+"Category='"+category+"',"+"Question='"+t2.getText()+"',"+"Option1='"+t3.getText()+"',"+"Option2='"+t4.getText()+"',"+"Option3='"+t5.getText()+"',"+"Option4='"+t6.getText()+"',"+"Answer='"+t7.getText()+"' "+"WHERE `S.No`='"+t1.getText()+"'");
                JOptionPane.showMessageDialog(this,"Question Updated Successfully !");
                t1.setText("");
t2.setText("");
t3.setText("");
t4.setText("");
t5.setText("");
t6.setText("");
t7.setText("");
C.select(0);
ResultSet rs1 = st.executeQuery("SELECT MAX(`S.No`) FROM questions");
if(rs1.next())
{
    int id = rs1.getInt(1);
    id = id + 1;
    t1.setText(String.valueOf(id));
}
    }
    catch(Exception e)
    {
        System.out.print(e);
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt2MouseClicked
        // TODO add your handling code here:
        int i = jt2.getSelectedRow();
         try
        {
        rs.absolute(i + 1);
        String sno = rs.getString("S.No");
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection( "jdbc:mysql://localhost:3306/kbc_game","root","");
            Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
            ResultSet rs1 = st.executeQuery("SELECT * FROM questions WHERE `S.No`='"+sno+"'");
            if(rs1.next())
        {
            t1.setText(rs1.getString("S.No"));
            t2.setText(rs1.getString("Question"));
            t3.setText(rs1.getString("Option1"));
            t4.setText(rs1.getString("Option2"));
            t5.setText(rs1.getString("Option3"));
            t6.setText(rs1.getString("Option4"));
            t7.setText(rs1.getString("Answer"));
            C.select(rs1.getString("Category"));
        }
    }
catch(Exception e)
    {
        System.out.print(e);
    }
    }//GEN-LAST:event_jt2MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int i = jt2.getSelectedRow();
        if(i==-1)
    {
        JOptionPane.showMessageDialog(this,"Please Select A Question !");
    }
        else
    {
        int j = JOptionPane.showConfirmDialog(this,"Do you want to delete this question ?");
        if(j==0)
        {
            try
            {
                Class.forName("com.mysql.jdbc.Driver");
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
                Statement st = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_READ_ONLY);
                st.executeUpdate("DELETE FROM questions WHERE `S.No`='"+t1.getText()+"'");
                JOptionPane.showMessageDialog(this,"Question Deleted Successfully !");
                t1.setText("");
t2.setText("");
t3.setText("");
t4.setText("");
t5.setText("");
t6.setText("");
t7.setText("");
C.select(0);
ResultSet rs1 = st.executeQuery("SELECT MAX(`S.No`) FROM questions");
if(rs1.next())
{
    int id = rs1.getInt(1);
    id = id + 1;
    t1.setText(String.valueOf(id));
}
            }
            catch(Exception e)
            {
                System.out.print(e);
            }
        }
    }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ADMIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ADMIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Choice C;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JComboBox<String> c2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jt2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l7;
    private javax.swing.JLabel l8;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    // End of variables declaration//GEN-END:variables
}
