/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import javax.swing.*;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.Statement;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author gagne
 */
public class gameover extends javax.swing.JFrame {

    /**
     * Creates new form gameover
     */
    public gameover() {
        initComponents();
        if(LOGIN.guestMode)
    {
        b1.setVisible(false);
    }
        setTitle("KBC GAME");
         this.setBounds(1, 1, 1880, 870);
    }
    String email;
    String playername;
    int prize;
    public gameover(int score, String email,String pname) {
        this.email = email;
        this.playername = pname;
         initComponents();
         setTitle("KBC GAME");
         if(LOGIN.guestMode)
{
    b1.setVisible(false);
}
         this.setBounds(1, 1, 1880, 870);
        prize=score*1000;
                l1.setText(score + "");
                l2.setText(" ₹ " + prize);
                if(prize > 0)
                {
                    try
                    {
                        AudioInputStream audio =AudioSystem.getAudioInputStream(getClass().getResource("/game/clap.wav"));
                        Clip clip = AudioSystem.getClip();
                        clip.open(audio);
                        clip.start();
                    }
                catch(Exception e)
                        {
                        System.out.println(e);
                        }
    }
                if(!LOGIN.guestMode)
{
                try
                {
                    Class.forName("com.mysql.jdbc.Driver");
                    Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
                    Statement st = con.createStatement();
                    int i = st.executeUpdate("INSERT INTO player_history(Email,Name,Score,Prize_Money) VALUES('"+ email + "','"+ playername + "','"+ score + "','"+prize+"')");
                }
                catch(Exception e)
{
    System.out.println(e);
}
}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        b = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(null);

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/close4.png"))); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b);
        b.setBounds(1020, 720, 270, 70);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Thank You For Playing !");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(770, 190, 360, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/gameover.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(630, 10, 650, 170);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/KBC.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(1560, 10, 230, 200);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/KBC.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(100, 0, 230, 200);

        jLabel5.setFont(new java.awt.Font("Segoe Print", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 215, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Hope You Enjoyed The Game .");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(750, 230, 390, 50);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/diamond.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(710, 200, 40, 60);

        jSeparator2.setBackground(new java.awt.Color(255, 215, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 215, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(300, 230, 410, 30);

        jSeparator3.setBackground(new java.awt.Color(255, 215, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 215, 0));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(1170, 230, 400, 30);

        jPanel2.setBackground(new java.awt.Color(10, 25, 70));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 2, true));
        jPanel2.setToolTipText("");
        jPanel2.setLayout(null);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/score.png"))); // NOI18N
        jPanel2.add(jLabel6);
        jLabel6.setBounds(10, 20, 130, 130);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/money.png"))); // NOI18N
        jPanel2.add(jLabel7);
        jLabel7.setBounds(0, 190, 140, 120);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("PRIZE MONEY  :");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(160, 210, 370, 70);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 40)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("YOUR SCORE    :");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(160, 50, 370, 70);
        jPanel2.add(jSeparator1);
        jSeparator1.setBounds(550, 160, 410, 20);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(70, 160, 430, 20);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/diamond.png"))); // NOI18N
        jPanel2.add(jLabel8);
        jLabel8.setBounds(510, 140, 30, 40);

        l2.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(l2);
        l2.setBounds(520, 220, 370, 60);

        l1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel2.add(l1);
        l1.setBounds(510, 60, 370, 60);

        jLabel16.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel16);
        jLabel16.setBounds(530, 50, 270, 60);

        jLabel18.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel18);
        jLabel18.setBounds(520, 50, 270, 60);

        jLabel19.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel19);
        jLabel19.setBounds(530, 50, 270, 60);

        jLabel20.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel20);
        jLabel20.setBounds(530, 50, 270, 60);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(460, 330, 1010, 340);

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/diamond.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1140, 200, 40, 60);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/replay.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(620, 720, 320, 70);

        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/bggmeover.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, 0, 1910, 830);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-20, 0, 1930, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
        LOGIN.guestMode = false;
        LOGIN L2=new LOGIN();
        L2.setSize(1880,870);
        L2.setVisible(true);
          this.dispose();
    }//GEN-LAST:event_bActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        WELCOME W2=new WELCOME(email);
        W2.setSize(1880,870);
        W2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gameover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gameover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gameover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gameover.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gameover().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    // End of variables declaration//GEN-END:variables
}
