/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.awt.Checkbox;
import java.awt.CheckboxGroup;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import java.awt.Color;
import java.awt.event.*;
import java.sql.Blob;
import java.awt.Image;
import java.sql.PreparedStatement;

/**
 *
 * @author gagne
 */
public class game1 extends javax.swing.JFrame {

    /**
     * Creates new form game1
     */
    String email;
    int chances = 0;
    String money;
    int currentQuestion = 1;
    int Score = 0;
    String playername;
        ResultSet rs;
        String correctanswer="";
        int i=0;
        int k=0;
        int j,randomid,count;
        int a[]=new int[100];
        int C;
        int time= 30;
        Timer t;
        public game1(String pname, String email)
        {
            initComponents();
            setTitle("KBC GAME");
            this.email = email;
            playername = pname;
            l1.setText(playername);
            loadPlayerPhoto();
            this.setBounds(1, 1, 1880, 870);
            count = -1;
            try
            {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
            Statement st = con.createStatement();
            rs = st.executeQuery("SELECT COUNT(*) FROM questions");
            if(rs.next())
            {
                C = rs.getInt(1);
            }
            randomid = (int)(Math.random()*C)+1;
            rs = st.executeQuery("SELECT * FROM questions WHERE `S.No`=" + randomid);
            if(rs.next())
            {
            l5.setText("QUESTION NO : " + (i+1));
            l2.setText(rs.getString("Category"));
            l3.setText(rs.getString("Question"));
            c1.setText(rs.getString("Option1"));
            c2.setText(rs.getString("Option2"));
            c3.setText(rs.getString("Option3"));
            c4.setText(rs.getString("Option4"));
            correctanswer = rs.getString("Answer");
            startTimer();
        }
    }
            catch(Exception em)
    {
        System.out.print(em);
    }
            System.out.print(i);
            count = count + 1;
            a[count] = randomid;
            System.out.print(randomid);
}
        public void startTimer()
{
    time = 30;
    jLabel8.setText(String.valueOf(time));
    t = new Timer(1000,new ActionListener()
    {
        public void actionPerformed(ActionEvent e)
        {
            time--;
            jLabel8.setText(String.valueOf(time));
            if(time <= 10)
            {
                jLabel8.setForeground(Color.RED);
            }
            else
            {
                jLabel8.setForeground(Color.WHITE);
            }
            if(time <= 5)
            {
                if(time % 2 == 0)
                {
                    jLabel8.setForeground(Color.RED);
                }
                else
                {
                    jLabel8.setForeground(Color.YELLOW);
                }
            }
            if(time == 0)
            {
                t.stop();
                dispose();
                gameover g = new gameover(Score,email,playername);
                g.setSize(1880,870);
                g.setVisible(true);
            }
        }
    });
    t.start();
}
        private void loadPlayerPhoto()
{
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con =DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
        PreparedStatement ps =con.prepareStatement("SELECT Photo FROM register WHERE Email=?");
        ps.setString(1,email);
        ResultSet rs = ps.executeQuery();
        if(rs.next())
        {
            Blob blob = rs.getBlob("photo");
            if(blob != null)
            {
                byte[] imageBytes =blob.getBytes(1,(int)blob.length());
                ImageIcon icon =new ImageIcon(imageBytes);
                Image img =icon.getImage().getScaledInstance(jLabel2.getWidth(),jLabel2.getHeight(),Image.SCALE_SMOOTH);
                jLabel2.setIcon(new ImageIcon(img));
            }
        }
        rs.close();
        ps.close();
        con.close();
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        l3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        l4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        b = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        c1 = new javax.swing.JRadioButton();
        jPanel5 = new javax.swing.JPanel();
        c3 = new javax.swing.JRadioButton();
        jPanel6 = new javax.swing.JPanel();
        c2 = new javax.swing.JRadioButton();
        jPanel7 = new javax.swing.JPanel();
        c4 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        b5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        l5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        l7 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/game.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(750, 0, 540, 210);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/playername.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 130, 90, 80);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/category2.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(840, 130, 100, 80);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 215, 0));
        jLabel4.setText("CATEGORY");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(940, 130, 110, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 215, 0));
        jLabel6.setText("TIME LEFT");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(1460, 130, 130, 30);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/TIME.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(1360, 140, 110, 80);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 19)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 215, 0));
        jLabel7.setText("PLAYER NAME");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(440, 130, 160, 30);

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 19)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jLabel8);
        jLabel8.setBounds(1470, 170, 100, 40);

        l1.setFont(new java.awt.Font("Perpetua Titling MT", 1, 19)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(l1);
        l1.setBounds(450, 170, 170, 40);

        l2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 19)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(l2);
        l2.setBounds(950, 170, 280, 40);

        jSeparator1.setBackground(new java.awt.Color(255, 215, 0));
        jPanel1.add(jSeparator1);
        jSeparator1.setBounds(1070, 230, 480, 40);

        jSeparator2.setBackground(new java.awt.Color(255, 215, 0));
        jPanel1.add(jSeparator2);
        jSeparator2.setBounds(390, 370, 1160, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 215, 0));
        jLabel11.setText("LIFELINES");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(910, 200, 140, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/diamond.png"))); // NOI18N
        jPanel1.add(jLabel12);
        jLabel12.setBounds(880, 210, 40, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/diamond.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(360, 210, 40, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/diamond.png"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(350, 350, 40, 40);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/diamond.png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(1040, 210, 40, 40);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 215, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("CHOOSE CATEGORY");
        jPanel1.add(jLabel19);
        jLabel19.setBounds(430, 340, 230, 30);

        jLabel20.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 215, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("50:50");
        jPanel1.add(jLabel20);
        jLabel20.setBounds(810, 330, 60, 50);

        jSeparator3.setBackground(new java.awt.Color(255, 215, 0));
        jPanel1.add(jSeparator3);
        jSeparator3.setBounds(390, 230, 490, 40);

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/diamond.png"))); // NOI18N
        jPanel1.add(jLabel22);
        jLabel22.setBounds(1550, 210, 40, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/diamond.png"))); // NOI18N
        jPanel1.add(jLabel23);
        jLabel23.setBounds(1550, 350, 40, 40);

        jPanel2.setBackground(new java.awt.Color(10, 25, 70));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 3, true));
        jPanel2.setLayout(null);

        l3.setBackground(new java.awt.Color(10, 25, 30));
        l3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setToolTipText("");
        jPanel2.add(l3);
        l3.setBounds(120, 10, 1440, 70);

        jPanel3.setBackground(new java.awt.Color(10, 25, 70));
        jPanel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 3, true));
        jPanel3.setLayout(null);

        l4.setBackground(new java.awt.Color(10, 25, 30));
        l4.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 255, 255));
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setText("jLabel25");
        l4.setToolTipText("");
        jPanel3.add(l4);
        l4.setBounds(140, 10, 890, 70);

        jPanel2.add(jPanel3);
        jPanel3.setBounds(160, 400, 1060, 90);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/qm.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(-40, 0, 150, 100);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(210, 440, 1530, 90);

        b.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/submit.png"))); // NOI18N
        b.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActionPerformed(evt);
            }
        });
        jPanel1.add(b);
        b.setBounds(660, 760, 300, 50);

        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/quit1.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel1.add(b1);
        b1.setBounds(1020, 760, 300, 50);

        jPanel4.setBackground(new java.awt.Color(10, 25, 70));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 3, true));
        jPanel4.setLayout(null);

        c1.setBackground(new java.awt.Color(10, 25, 70));
        buttonGroup1.add(c1);
        c1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        c1.setForeground(new java.awt.Color(255, 255, 255));
        c1.setIconTextGap(20);
        c1.setInheritsPopupMenu(true);
        c1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c1ActionPerformed(evt);
            }
        });
        jPanel4.add(c1);
        c1.setBounds(40, 10, 660, 50);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(210, 550, 710, 70);

        jPanel5.setBackground(new java.awt.Color(10, 25, 70));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 3, true));
        jPanel5.setLayout(null);

        c3.setBackground(new java.awt.Color(10, 25, 70));
        buttonGroup1.add(c3);
        c3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        c3.setForeground(new java.awt.Color(255, 255, 255));
        c3.setIconTextGap(20);
        c3.setInheritsPopupMenu(true);
        c3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                c3ActionPerformed(evt);
            }
        });
        jPanel5.add(c3);
        c3.setBounds(40, 10, 660, 50);

        jPanel1.add(jPanel5);
        jPanel5.setBounds(210, 650, 710, 70);

        jPanel6.setBackground(new java.awt.Color(10, 25, 70));
        jPanel6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 3, true));
        jPanel6.setLayout(null);

        c2.setBackground(new java.awt.Color(10, 25, 70));
        buttonGroup1.add(c2);
        c2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        c2.setForeground(new java.awt.Color(255, 255, 255));
        c2.setIconTextGap(20);
        c2.setInheritsPopupMenu(true);
        jPanel6.add(c2);
        c2.setBounds(40, 10, 640, 50);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(1040, 550, 700, 70);

        jPanel7.setBackground(new java.awt.Color(10, 25, 70));
        jPanel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 3, true));
        jPanel7.setLayout(null);

        c4.setBackground(new java.awt.Color(10, 25, 70));
        buttonGroup1.add(c4);
        c4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        c4.setForeground(new java.awt.Color(255, 255, 255));
        c4.setIconTextGap(20);
        c4.setInheritsPopupMenu(true);
        jPanel7.add(c4);
        c4.setBounds(40, 10, 620, 50);

        jPanel1.add(jPanel7);
        jPanel7.setBounds(1040, 650, 700, 70);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/trophy.png"))); // NOI18N
        jPanel1.add(jLabel10);
        jLabel10.setBounds(1680, 10, 190, 200);

        jLabel26.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/trophy.png"))); // NOI18N
        jPanel1.add(jLabel26);
        jLabel26.setBounds(10, 10, 180, 190);

        b5.setBackground(new java.awt.Color(10, 25, 70));
        b5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/category3.png"))); // NOI18N
        b5.setBorder(null);
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel1.add(b5);
        b5.setBounds(490, 250, 100, 90);

        jButton2.setBackground(new java.awt.Color(10, 25, 70));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/50-50.png"))); // NOI18N
        jButton2.setBorder(null);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(790, 250, 100, 90);

        jPanel8.setBackground(new java.awt.Color(10, 25, 70));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 2, true));
        jPanel8.setLayout(null);

        l5.setFont(new java.awt.Font("Times New Roman", 1, 27)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 215, 0));
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel8.add(l5);
        l5.setBounds(20, 0, 310, 50);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(820, 380, 340, 50);

        jButton1.setBackground(new java.awt.Color(10, 25, 70));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/skip.png"))); // NOI18N
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1080, 250, 100, 90);

        b4.setBackground(new java.awt.Color(10, 25, 70));
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/2x.png"))); // NOI18N
        b4.setBorder(null);
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel1.add(b4);
        b4.setBounds(1350, 250, 100, 90);

        jLabel21.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 215, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("SKIP QUESTION");
        jPanel1.add(jLabel21);
        jLabel21.setBounds(1040, 330, 170, 50);

        jLabel27.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 215, 0));
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel27.setText("TWO CHANCES");
        jPanel1.add(jLabel27);
        jLabel27.setBounds(1310, 340, 170, 30);

        l7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(l7);
        l7.setBounds(930, 590, 100, 110);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/bggame.png"))); // NOI18N
        jPanel1.add(jLabel16);
        jLabel16.setBounds(10, 0, 1920, 840);

        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/trophy.png"))); // NOI18N
        jPanel1.add(jLabel17);
        jLabel17.setBounds(1680, 10, 190, 200);

        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/trophy.png"))); // NOI18N
        jPanel1.add(jLabel18);
        jLabel18.setBounds(1680, 10, 190, 200);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(-10, 0, 1930, 850);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        gameover g5 = new gameover(Score,email,playername);
        g5.setSize(1880,870);
        g5.setVisible(true);
    }//GEN-LAST:event_b1ActionPerformed

    private void bActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActionPerformed
        // TODO add your handling code here:
        String userAns = "";
        if(c1.isSelected()) userAns = c1.getText();
        else if(c2.isSelected()) userAns = c2.getText();
        else if(c3.isSelected()) userAns = c3.getText();
        else if(c4.isSelected()) userAns = c4.getText();
        else
        {
            System.out.println("Please select an option");
            return;
        }
        if(userAns.equals(correctanswer))
        {
            Score++;
            currentQuestion++;
            i++;
            if(LOGIN.guestMode && currentQuestion > 3)
{
           JOptionPane.showMessageDialog( this, "GUEST  DEMO  FINISHED!\nLOGIN / REGISTER  TO  PLAY  THE  FULL  GAME.");
    this.dispose();
    gameover g = new gameover(Score,email,playername);
    g.setSize(1880,860);
    g.setVisible(true);
    return;
}
            chances = 0;
            l5.setText("QUESTION NO : " + (i+1));
            try
            {
                if(count >= C-1)
{
    this.dispose();

    gameover o = new gameover(Score,email,playername);
    o.setSize(1880,860);
    o.setVisible(true);

    return;
}
                while(true)
                {
                    randomid=(int)(Math.random()*C)+1;
                    for(k=0;k<=count;k++)
                    {
                        if(a[k]==randomid)
                            break;
                    }
                    if(k>count)
                    {
                        count=count+1;
                        a[count]=randomid;
                        break;
                    }
                }
                Class.forName("com.mysql.jdbc.Driver");
                Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
                Statement st = con.createStatement();
                rs= st.executeQuery("SELECT  COUNT(*) FROM questions");
                int c=0;
                if(rs.next())
                {
                    c=rs.getInt(1);
                }
                rs=st.executeQuery("SELECT * FROM questions WHERE `S.No`=" + randomid);
                if(rs.next())
                {
                    l2.setText( rs.getString("Category"));
                    l3.setText( rs.getString("Question"));
                    c1.setText(rs.getString("Option1"));
                    c2.setText(rs.getString("Option2"));
                    c3.setText(rs.getString("Option3"));
                    c4.setText(rs.getString("Option4"));
                    correctanswer=(rs.getString("Answer"));
                    buttonGroup1.clearSelection();
                    c1.setVisible(true);
                    c2.setVisible(true);
                    c3.setVisible(true);
                    c4.setVisible(true);
                    l7.setIcon(null);
                    t.stop();
startTimer();
                }
            }
            catch(Exception em)
            {
                System.out.print(em);
            }
        }
        else
        {
            if(chances==2)
            {
            chances--;
             JOptionPane.showMessageDialog(this,"WRONG ANSWER ! TRY ONE MORE TIME.");
              buttonGroup1.clearSelection();
              return;
        }
        else 
        {
            this.dispose();
            gameover o=new gameover(Score, email,playername);
            o.setSize(1880,870);
            o.setVisible(true);
        }
        }
    }//GEN-LAST:event_bActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        // TODO add your handling code here:
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection( "jdbc:mysql://localhost:3306/kbc_game","root","");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery("SELECT DISTINCT Category FROM questions");
            JComboBox<String> combo = new JComboBox<>();
            while(rs.next())
            {
                combo.addItem(rs.getString("Category"));
            }
            int k = JOptionPane.showConfirmDialog(this,combo,"Choose Category",JOptionPane.OK_CANCEL_OPTION);
            if(k == JOptionPane.OK_OPTION)
            {
                String selectedCategory = combo.getSelectedItem().toString();
                l2.setText(selectedCategory);
                ResultSet rs2 = st.executeQuery("SELECT * FROM questions WHERE Category='" + selectedCategory + "' ORDER BY RAND() LIMIT 1");
                if(rs2.next())
                {
                    l3.setText(rs2.getString("Question"));
                    c1.setText(rs2.getString("Option1"));
                    c2.setText(rs2.getString("Option2"));
                    c3.setText(rs2.getString("Option3"));
                    c4.setText(rs2.getString("Option4"));
                    correctanswer = rs2.getString("Answer");
                    buttonGroup1.clearSelection();
                    c1.setVisible(true);
                    c2.setVisible(true);
                    c3.setVisible(true);
                    c4.setVisible(true);
                }
                l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/category(4).png")));
                b5.setEnabled(false);
            }
        }
        catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         JRadioButton arr[] = {c1, c2, c3, c4};
         int correctIndex = -1;
         for(int i=0; i<4; i++)
         {
             if(arr[i].getText().equals(correctanswer))
             {
                 correctIndex = i;
                 break;
             }
         }
         int randomWrong;
         do
         {
             randomWrong = (int)(Math.random()*4);
         }
         while(randomWrong == correctIndex);
         for(int i=0; i<4; i++)
         {
             if(i != correctIndex && i != randomWrong)
             {
                 arr[i].setVisible(false);
             }
         }
         l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/50.png")));
         jButton2.setEnabled(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void c1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c1ActionPerformed

    private void c3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_c3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_c3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try
        {
            if(count >= C-1)
{
    this.dispose();

    gameover o = new gameover(Score,email,playername);
    o.setSize(1880,860);
    o.setVisible(true);

    return;
}
            while(true)
        {
            randomid = (int)(Math.random()*C)+1;

            for(k=0; k<=count; k++)
            {
                if(a[k] == randomid)
                {
                    break;
                }
            }
            if(k > count)
            {
                count = count + 1;
                a[count] = randomid;
                break;
            }
        }
          Class.forName("com.mysql.jdbc.Driver");
           Connection con = DriverManager.getConnection( "jdbc:mysql://localhost:3306/kbc_game","root","");
           Statement st = con.createStatement();
           rs=st.executeQuery("SELECT * FROM questions WHERE `S.No`=" + randomid);
            if(rs.next())
        {
                    l2.setText( rs.getString("Category"));
                    l3.setText( rs.getString("Question"));
                    c1.setText(rs.getString("Option1"));
                    c2.setText(rs.getString("Option2"));
                    c3.setText(rs.getString("Option3"));
                    c4.setText(rs.getString("Option4"));
                    correctanswer=(rs.getString("Answer"));
                    c1.setVisible(true);
                    c2.setVisible(true);
                    c3.setVisible(true);
                    c4.setVisible(true);
                    buttonGroup1.clearSelection();
                    l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/skip1.png")));
                    jButton1.setEnabled(false);
                    l7.setIcon(null);
                    t.stop();
startTimer();
        }
        }
        catch(Exception el)
                {
                    System.out.print(el);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
         chances = 2;
        {
            JOptionPane.showMessageDialog(this,"YOU HAVE 2 CHANCES FOR THIS QUESTION !");
        }
        
         l7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/2x(1).png")));
        b4.setEnabled(false);
    }//GEN-LAST:event_b4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(game1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b;
    private javax.swing.JButton b1;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton c1;
    private javax.swing.JRadioButton c2;
    private javax.swing.JRadioButton c3;
    private javax.swing.JRadioButton c4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l7;
    // End of variables declaration//GEN-END:variables
}
