/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author gagne
 */
public class LOGIN extends javax.swing.JFrame {

    /**
     * Creates new form LOGIN
     */
    public static boolean guestMode = false;
    public LOGIN() {
        initComponents();
        this.setBounds(1, 1, 1880, 870); 
        setTitle("KBC GAME");
        l4.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        l3 = new javax.swing.JLabel();
        B3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        l4 = new javax.swing.JLabel();
        t2 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setForeground(new java.awt.Color(0, 0, 255));
        jPanel2.setLayout(null);

        l1.setBackground(new java.awt.Color(255, 255, 0));
        l1.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 50)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 223, 88));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/kbc1.png"))); // NOI18N
        jPanel2.add(l1);
        l1.setBounds(570, 10, 770, 260);

        l2.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/email.png"))); // NOI18N
        jPanel2.add(l2);
        l2.setBounds(580, 380, 90, 50);

        t1.setFont(new java.awt.Font("Cambria", 1, 27)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 255, 255), 2, true));
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });
        jPanel2.add(t1);
        t1.setBounds(730, 370, 500, 70);

        l3.setFont(new java.awt.Font("Bookman Old Style", 1, 30)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/psswd.png"))); // NOI18N
        jPanel2.add(l3);
        l3.setBounds(580, 470, 90, 70);

        B3.setBackground(new java.awt.Color(153, 204, 255));
        B3.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        B3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/close.png"))); // NOI18N
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        jPanel2.add(B3);
        B3.setBounds(1120, 720, 300, 80);

        b4.setBackground(new java.awt.Color(255, 153, 153));
        b4.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        b4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/admin.png"))); // NOI18N
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel2.add(b4);
        b4.setBounds(720, 720, 350, 80);

        B2.setBackground(new java.awt.Color(255, 255, 153));
        B2.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        B2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/register.png"))); // NOI18N
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        jPanel2.add(B2);
        B2.setBounds(340, 720, 320, 80);

        b1.setBackground(new java.awt.Color(51, 204, 0));
        b1.setFont(new java.awt.Font("Gabriola", 1, 40)); // NOI18N
        b1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/login.png"))); // NOI18N
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1);
        b1.setBounds(40, 720, 250, 80);

        l4.setBackground(new java.awt.Color(255, 255, 255));
        l4.setFont(new java.awt.Font("Segoe Script", 1, 18)); // NOI18N
        l4.setForeground(new java.awt.Color(255, 51, 51));
        l4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/invalid.png"))); // NOI18N
        jPanel2.add(l4);
        l4.setBounds(830, 570, 300, 56);

        t2.setFont(new java.awt.Font("Cambria", 1, 27)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });
        jPanel2.add(t2);
        t2.setBounds(730, 470, 500, 75);

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Welcome to KBC Game");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(790, 250, 360, 50);

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 28)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Login to Continue your journey ! ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(730, 290, 500, 30);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/forgot2.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1);
        jButton1.setBounds(1480, 720, 350, 80);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/guest.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(830, 640, 300, 50);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/bglogin.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(0, 0, 1870, 830);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1950, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        // TODO add your handling code here:
         l4.setVisible(false);
        if(t1.getText().trim().length()==0 || t2.getText().trim().length()==0)
    {
        JOptionPane.showMessageDialog(this,"PLEASE  ENTER  YOUR  DETAILS !");
    }
            else if(!t1.getText().contains("@gmail.com"))
            {
              JOptionPane.showMessageDialog(this,"EMAIL  MUST  CONTAIN  (@gmail.com)");
            }
else
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection C=DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
            Statement St = C.createStatement();
            ResultSet RS=St.executeQuery("Select * from register where Email='"+t1.getText()+"' and Password='"+t2.getText()+"'");
            if(RS.next())
            {
                LOGIN.guestMode = false;
                WELCOME W1=new WELCOME(t1.getText());
                W1.setSize(1880,870);
                W1.setVisible(true);
                this.dispose();
            }
            else
            {
                l4.setVisible(true);
            }
        }
        catch(Exception e)
        {
            System.out.print(e);
        }
    }
    }//GEN-LAST:event_b1ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        // TODO add your handling code here:\
        REGISTER R2=new REGISTER();
        R2.setSize(1880,870);
        R2.setVisible(true);
    }//GEN-LAST:event_B2ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        // TODO add your handling code here:
         l4.setVisible(false);
        String u=t1.getText();
        String p=t2.getText();
        if(t1.getText().trim().length()==0 || t2.getText().trim().length()==0)
    {
        JOptionPane.showMessageDialog(this,"PLEASE  ENTER  YOUR  DETAILS !");
    }
        else if(!t1.getText().contains("@gmail.com"))
            {
              JOptionPane.showMessageDialog(this,"EMAIL  MUST  CONTAIN  (@gmail.com)");
            }
    else
    {
        if(u.equals("ag@gmail.com")&& p.equals("2580"))
            {
                ADMIN A2=new ADMIN();   
                A2.setSize(1880,870);
                A2.setVisible(true);
}
        else
            {
                l4.setVisible(true);
            }
    }
    }//GEN-LAST:event_b4ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        // TODO add your handling code here:
        int i=JOptionPane.showConfirmDialog(this,"DO  YOU  WANT  TO  END  THE  GAME  ?","EXIT GAME",JOptionPane.YES_NO_OPTION);
        if(i==JOptionPane.YES_OPTION)
        dispose();
    }//GEN-LAST:event_B3ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t1ActionPerformed

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
    {
        evt.consume();
    }
        if(t2.getText().length() >= 4)
    {
        evt.consume();
    }
    }//GEN-LAST:event_t2KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try
        {
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery("SELECT * FROM register WHERE Email='"+ t1.getText() + "'");
        if(rs.next())
        {
         forgot f1 = new forgot(t1.getText());
    f1.setVisible(true);
    f1.setSize(1880,870);
        }
        else
             {
            JOptionPane.showMessageDialog(this,"Please enter your Email !");
        }
        }
        catch(Exception e4)
        {
            System.out.print(e4);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         guestMode = true; 
         play p1 = new play("Guest","guest@gmail.com");
    p1.setSize(1880,870);
    p1.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LOGIN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LOGIN().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton b1;
    private javax.swing.JButton b4;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l4;
    private javax.swing.JTextField t1;
    private javax.swing.JPasswordField t2;
    // End of variables declaration//GEN-END:variables
}
