/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

/**
 *
 * @author gagne
 */
public class play extends javax.swing.JFrame implements Runnable {

    /**
     * Creates new form play
     */
    String email;
    String pname;
    Thread t;
    int i;
        public play(String pname, String email) {
            initComponents();
            setTitle("KBC GAME");
            this.setBounds(1, 1, 1880, 870);
            this.pname = pname;
        this.email = email;
            t=new Thread(this);
            i=1;
        }
        public void run()
        {
            for(;i<=100;i++)
            {
                try
                {
                    pb1.setValue(i);
                    t.sleep(70);
                }
                catch(Exception e)
                {
                    System.out.print(e);
                }
            }
            game1 g1=new game1(pname,email);
            g1.setVisible(true);
            g1.setSize(1880,870);
            dispose();
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        pb1 = new javax.swing.JProgressBar();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setLayout(null);

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/getting2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(590, 20, 670, 160);

        jPanel2.setBackground(new java.awt.Color(0, 51, 153));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 2, true));
        jPanel2.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("ultimate champion !");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(80, 520, 290, 30);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/rules1.png"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(110, 20, 470, 80);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("You have 30 seconds to answer each question. The");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(80, 220, 640, 30);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("timer will start as soon as the question appears.");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(80, 250, 500, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("You can use lifelines to help you answer the questions.");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(80, 440, 560, 30);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Try to answer all questions correctly and become the ");
        jPanel2.add(jLabel13);
        jLabel13.setBounds(80, 490, 570, 30);

        jLabel17.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("question.");
        jPanel2.add(jLabel17);
        jLabel17.setBounds(80, 320, 100, 30);

        jLabel18.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("If your answer is incorrect, the game will end. you");
        jPanel2.add(jLabel18);
        jLabel18.setBounds(80, 360, 520, 30);

        jLabel19.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("will take home the amount you have won.");
        jPanel2.add(jLabel19);
        jLabel19.setBounds(80, 390, 430, 30);
        jPanel2.add(jSeparator2);
        jSeparator2.setBounds(70, 480, 550, 30);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(70, 150, 540, 30);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(70, 210, 550, 30);
        jPanel2.add(jSeparator6);
        jSeparator6.setBounds(80, 290, 540, 10);
        jPanel2.add(jSeparator5);
        jSeparator5.setBounds(80, 350, 540, 30);
        jPanel2.add(jSeparator7);
        jSeparator7.setBounds(80, 430, 540, 10);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("There will be total of 20 questions.");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(80, 110, 510, 30);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/seven.png"))); // NOI18N
        jPanel2.add(jLabel15);
        jLabel15.setBounds(20, 500, 50, 50);

        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/one.png"))); // NOI18N
        jPanel2.add(jLabel20);
        jLabel20.setBounds(20, 100, 50, 50);

        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/two.png"))); // NOI18N
        jPanel2.add(jLabel21);
        jLabel21.setBounds(20, 160, 50, 50);

        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/three.png"))); // NOI18N
        jPanel2.add(jLabel22);
        jLabel22.setBounds(20, 220, 50, 50);

        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/four.png"))); // NOI18N
        jPanel2.add(jLabel23);
        jLabel23.setBounds(20, 300, 50, 50);

        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/five.png"))); // NOI18N
        jPanel2.add(jLabel24);
        jLabel24.setBounds(20, 360, 50, 50);

        jLabel25.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/six.png"))); // NOI18N
        jPanel2.add(jLabel25);
        jLabel25.setBounds(20, 430, 50, 50);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Each question has 4 options, out of which only one is");
        jLabel16.setToolTipText("");
        jPanel2.add(jLabel16);
        jLabel16.setBounds(80, 150, 540, 40);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("correct.");
        jLabel14.setToolTipText("");
        jPanel2.add(jLabel14);
        jLabel14.setBounds(80, 180, 90, 30);

        jLabel26.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("If your answer is correct, you will move to the next ");
        jPanel2.add(jLabel26);
        jLabel26.setBounds(80, 290, 530, 30);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(250, 130, 630, 570);

        jPanel4.setBackground(new java.awt.Color(0, 51, 153));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 215, 0), 2, true));
        jPanel4.setLayout(null);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/loading.png"))); // NOI18N
        jPanel4.add(jLabel3);
        jLabel3.setBounds(120, 20, 470, 80);
        jPanel4.add(jSeparator1);
        jSeparator1.setBounds(150, 220, 0, 140);

        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/load1.png"))); // NOI18N
        jPanel4.add(jLabel10);
        jLabel10.setBounds(180, 110, 320, 330);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("for the best experience...");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(230, 440, 260, 30);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Please wait while we set up everything");
        jPanel4.add(jLabel12);
        jLabel12.setBounds(160, 410, 410, 30);

        pb1.setBackground(new java.awt.Color(0, 0, 0));
        pb1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pb1.setForeground(new java.awt.Color(51, 51, 51));
        pb1.setToolTipText("");
        pb1.setName(""); // NOI18N
        pb1.setStringPainted(true);
        jPanel4.add(pb1);
        pb1.setBounds(30, 490, 600, 40);

        jPanel1.add(jPanel4);
        jPanel4.setBounds(970, 130, 650, 570);

        b2.setBackground(new java.awt.Color(255, 102, 102));
        b2.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 40)); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/start.png"))); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(510, 740, 400, 70);

        b3.setBackground(new java.awt.Color(255, 102, 102));
        b3.setFont(new java.awt.Font("Berlin Sans FB Demi", 1, 40)); // NOI18N
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/close4.png"))); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel1.add(b3);
        b3.setBounds(950, 740, 270, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/bgplay.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1910, 830);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1910, 830);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        t.start();
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        // TODO add your handling code here:s
        WELCOME W2=new WELCOME(email);
        W2.setSize(1950,870);
        W2.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_b3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(play.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new play("","").setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JProgressBar pb1;
    // End of variables declaration//GEN-END:variables
}
