/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package game;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.*;
import java.awt.*;
import java.io.File;
import java.io.FileInputStream;
import java.sql.PreparedStatement;

/**
 *
 * @author gagne
 */
public class REGISTER extends javax.swing.JFrame {

    /**
     * Creates new form REGISTER
     */
    private File selectedFile = null;
    String imagePath = "";
    public REGISTER() {
        initComponents();
        setTitle("KBC GAME");
        this.setBounds(1, 1, 1880, 870); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        t3 = new javax.swing.JTextField();
        t4 = new javax.swing.JTextField();
        l1 = new javax.swing.JLabel();
        l2 = new javax.swing.JLabel();
        l3 = new javax.swing.JLabel();
        b2 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        l5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        l6 = new javax.swing.JLabel();
        l8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 51, 153));
        jPanel1.setAutoscrolls(true);
        jPanel1.setLayout(null);

        t1.setFont(new java.awt.Font("Calisto MT", 1, 25)); // NOI18N
        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(t1);
        t1.setBounds(950, 170, 420, 60);

        t2.setFont(new java.awt.Font("Calisto MT", 1, 25)); // NOI18N
        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t2KeyTyped(evt);
            }
        });
        jPanel1.add(t2);
        t2.setBounds(950, 260, 420, 60);

        t3.setFont(new java.awt.Font("Calisto MT", 1, 25)); // NOI18N
        t3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(t3);
        t3.setBounds(950, 350, 420, 60);

        t4.setFont(new java.awt.Font("Calisto MT", 1, 25)); // NOI18N
        t4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t4.setText(" ");
        t4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                t4KeyTyped(evt);
            }
        });
        jPanel1.add(t4);
        t4.setBounds(950, 440, 420, 60);

        l1.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        l1.setForeground(new java.awt.Color(255, 255, 255));
        l1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l1.setText("EMAIL");
        jPanel1.add(l1);
        l1.setBounds(690, 160, 170, 80);

        l2.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        l2.setForeground(new java.awt.Color(255, 255, 255));
        l2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l2.setText("PASSWORD");
        jPanel1.add(l2);
        l2.setBounds(680, 250, 210, 80);

        l3.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        l3.setForeground(new java.awt.Color(255, 255, 255));
        l3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l3.setText("NAME");
        jPanel1.add(l3);
        l3.setBounds(700, 340, 150, 80);

        b2.setBackground(new java.awt.Color(102, 204, 255));
        b2.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        b2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/close4.png"))); // NOI18N
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel1.add(b2);
        b2.setBounds(990, 730, 270, 70);

        B1.setBackground(new java.awt.Color(102, 255, 102));
        B1.setFont(new java.awt.Font("Gabriola", 1, 48)); // NOI18N
        B1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/save3.png"))); // NOI18N
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        jPanel1.add(B1);
        B1.setBounds(680, 730, 270, 70);

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/mail.png"))); // NOI18N
        jPanel1.add(jLabel3);
        jLabel3.setBounds(590, 180, 50, 40);

        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/password.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(590, 260, 50, 60);

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/name.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(590, 350, 50, 60);

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/profile.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(580, 530, 70, 70);

        l5.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        l5.setForeground(new java.awt.Color(255, 255, 255));
        l5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l5.setText("MOBILE NO");
        jPanel1.add(l5);
        l5.setBounds(670, 430, 220, 80);

        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/mobile.png"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(580, 440, 70, 70);

        l6.setFont(new java.awt.Font("Comic Sans MS", 1, 32)); // NOI18N
        l6.setForeground(new java.awt.Color(255, 255, 255));
        l6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l6.setText("PROFILE PHOTO");
        jPanel1.add(l6);
        l6.setBounds(650, 520, 290, 80);

        l8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        l8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/picture.png"))); // NOI18N
        jPanel1.add(l8);
        l8.setBounds(950, 520, 160, 170);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/browse1.png"))); // NOI18N
        jButton1.setInheritsPopupMenu(true);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(1120, 580, 250, 50);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/game/bgreg1.png"))); // NOI18N
        jPanel1.add(jLabel2);
        jLabel2.setBounds(0, -10, 1880, 950);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1910, 840);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        // TODO add your handling code here:
        String d="";
        if(t1.getText().trim().length()==0 || t2.getText().trim().length()==0 || t3.getText().trim().length()==0 || t4.getText().trim().length()==0)
    {
        JOptionPane.showMessageDialog(this,"PLEASE  ENTER  YOUR  DETAILS !");
    }
            else if(!t1.getText().contains("@gmail.com"))
            {
              JOptionPane.showMessageDialog(this,"EMAIL  MUST  CONTAIN  (@gmail.com)");
            }
    else
    {
        try
        {
            Class.forName("com.mysql.jdbc.Driver");
            Connection C=DriverManager.getConnection("jdbc:mysql://localhost:3306/kbc_game","root","");
            PreparedStatement check =C.prepareStatement("SELECT * FROM register WHERE Email=?");
            check.setString(1, t1.getText());
            ResultSet RS = check.executeQuery();
            if(RS.next())
            {
                JOptionPane.showMessageDialog(this,"This Email ID Is Already Registered !");
            }
            else
            {
                PreparedStatement ps =C.prepareStatement("INSERT INTO register (Email,Password,Name,Mobile_no,Age,City,State,Aadhar_no,Photo)VALUES(?,?,?,?,?,?,?,?,?)");
                ps.setString(1,t1.getText());
        ps.setString(2,t2.getText());
        ps.setString(3,t3.getText());
        ps.setString(4,t4.getText());
        ps.setString(5,d);
        ps.setString(6,d);
        ps.setString(7,d);
        ps.setString(8,d);
        if(selectedFile == null)
        {
            JOptionPane.showMessageDialog(this,"Please Upload Your Image !");
    return;
}
        FileInputStream fis =new FileInputStream(selectedFile);
        ps.setBinaryStream(9, fis, (int)selectedFile.length());
        int i = ps.executeUpdate();
            if(i==1)
            {
            JOptionPane.showMessageDialog(this, "Registered Successfully !");
            {
                dispose();
            }
        }
        }
        }
        catch(Exception e1)
        {
            e1.printStackTrace();
        }
    }
    }//GEN-LAST:event_B1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_b2ActionPerformed

    private void t2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t2KeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if(!Character.isDigit(c))
    {
        evt.consume();
    }
        if(t2.getText().length() >= 4)
    {
        evt.consume();
    }
    }//GEN-LAST:event_t2KeyTyped

    private void t4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_t4KeyTyped
        // TODO add your handling code here:
        char m = evt.getKeyChar();
        if(!Character.isDigit(m))
        {
            evt.consume();
        }
        if(t4.getText().length()>=10)
        {
            evt.consume();
        }
    }//GEN-LAST:event_t4KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   JFileChooser chooser = new JFileChooser();
    int result = chooser.showOpenDialog(this);
    if(result == JFileChooser.APPROVE_OPTION){
        selectedFile = chooser.getSelectedFile();
        ImageIcon icon =new ImageIcon(selectedFile.getAbsolutePath());
        Image img =icon.getImage().getScaledInstance(l8.getWidth(),l8.getHeight(),Image.SCALE_SMOOTH);
        l8.setText("");
        l8.setIcon(new ImageIcon(img));
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(REGISTER.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new REGISTER().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton B1;
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel l1;
    private javax.swing.JLabel l2;
    private javax.swing.JLabel l3;
    private javax.swing.JLabel l5;
    private javax.swing.JLabel l6;
    private javax.swing.JLabel l8;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    // End of variables declaration//GEN-END:variables
}
